name: "Shared Configuration"
description: "Fetch configuration parameters from a shared .ini file and export as environment variables"
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  config_repo:
    description: "URL of the repository containing the configuration file"
    required: true
  config_file:
    description: "Path to the configuration file in the repository"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Export configuration from configuration repository
      run: |
        git clone ${{ inputs.config_repo }} config-repo
        echo "Parsing configuration file: ${{ inputs.config_file }}"
        section=""
        while IFS= read -r line; do
          if [[ $(echo "$line" | tr -d '\r') =~ ^\[.*\]$ ]]; then
            section=$(echo "$line" | tr -d '\r' | sed -e 's/^\[\(.*\)\]$/\1/')
          elif [[ $line =~ ^[^#]*=.*$ ]]; then
            key=$(echo $line | cut -d '=' -f 1 | tr -d ' ' | tr -d '\t')
            
            if [[ $line =~ ^[^=]*=[[:space:]]*\"(.*)\"[[:space:]]*$ ]]; then
              # If the value is quoted, extract content without quotes
              value="${BASH_REMATCH[1]}"
            else
              # Otherwise use the previous method for unquoted values
              value=$(echo $line | cut -d '=' -f 2- | sed 's/^ *//;s/ *$//')
            fi
            
            env_var=$(echo "${section}_${key}" | tr '[:lower:]' '[:upper:]')
            echo "$env_var=$value" >> $GITHUB_ENV
          fi
        done < config-repo/${{ inputs.config_file }}
      shell: bash
