name: "Shared Configuration"
description: "Fetch configuration parameters from a shared .ini file and export as environment variables or outputs"
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  config_repo:
    description: "URL of the repository containing the configuration file"
    required: false
    default: ""
  use_output:
    description: "Set outputs using GITHUB_OUTPUT instead of GITHUB_ENV"
    required: false
    default: "false"
  config_file:
    description: "Path to the INI configuration file (relative to the repository root)"
    required: false
    default: "config.ini"
  force_uppercase:
    description: "Force use of uppercase in variable names. Default is true for environment variables, false for outputs"
    required: false
runs:
  using: 'node20'
  main: 'action.js'
